name: تحديث وقت آخر تعديل
on:
  push:
    branches: [ main, master ]
jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: تحديث ملف last-update.txt
        run: |
          echo "آخر تحديث: $(date '+%d %B %Y – %H:%M:%S')" > last-update.txt
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last-update.txt
          git commit -m "تحديث وقت آخر تعديل [skip ci]" || echo "لا تغييرات"
          git push